steps:
  # build and push docker image
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --build-arg
      - NODE_ENV=$_NODE_ENV
      - --cache-repo=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:latest
      - --destination=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - --cache=true
      - --cache-ttl=24h
    id: 'Docker Build and Push'
  # run cloudrun app
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - '-c'
      - |
       gcloud beta run deploy $_SERVICE_NAME --platform=managed \
        --image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA \
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID \
        --region=$_DEPLOY_REGION --quiet --port=8080 --timeout=300 --min-instances=1 --max-instances=2 \
        --no-cpu-throttling --allow-unauthenticated --execution-environment=gen1 \
        --set-env-vars NODE_ENV=$_NODE_ENV \
        --set-env-vars GCP_PROJECT_ID=$_GCP_PROJECT_ID \
        --set-env-vars GCP_CLIENT_EMAIL=$_GCP_CLIENT_EMAIL \
        --set-env-vars LOCKER_DOCUMENT_BUCKET=$_LOCKER_DOCUMENT_BUCKET \
        --set-env-vars MONGO_URI=$$MONGO_URI \
        --set-env-vars MONGO_DB_NAME=$_MONGO_DB_NAME \
        --set-env-vars GLOBAL_FILE_MANAGER_CLOUD_PROVER=$_GLOBAL_FILE_MANAGER_CLOUD_PROVER \
    id: 'Cloud Run Deploy'
    entrypoint: bash
options:
  secretEnv: ['MONGO_URI']    
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/MONGO_URI/versions/latest
    env: MONGO_URI
timeout: 1000s
